#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running lint check..."
bun run lint:check

if [ $? -ne 0 ]; then
  echo "❌ Lint failed. Please fix lint errors before committing."
  exit 1
fi

echo "✅ Lint passed. Proceeding with commit."
